### ISSUE TITLE
Larger Images

### ISSUE THREAD

**Issue by ljstrnadiii** [dancsalo/TensorBase#6]
@dancsalo , 

Very cool that you implemented this! In the paper, it says that this should work for "arbitrary" sized images. Have you tried this method with any large images?

Also, sorry for making an issue of this. I can delete if you prefer.

**Comment by dancsalo** [comment]
Hi @ljstrnadiii, I have not tried the algorithm with larger images or images that do not have all the same dimensions. The TF mechanics of processing images of different sizes is not streamlined; most papers resize the images to the same dimensions before feeding them through the net.
